name: Node.js CI/CD Pipeline

on:
  push:
    branches: [prod]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/avalista-be:latest .
          docker push $DOCKERHUB_USERNAME/avalista-be:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            DOCKER_USER="${DOCKERHUB_USERNAME}"
            echo "Iniciando deploy com usuário Docker: ${DOCKER_USER}"

            docker pull ${DOCKER_USER}/avalista-be:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app \
              -p 80:3000 \
              -e DATABASE_URL="$DATABASE_URL" \
              -e JWT_SECRET="$JWT_SECRET" \
              -e JWT_EXPIRE="$JWT_EXPIRE" \
              -e AWS_S3_BUCKET="$AWS_S3_BUCKET" \
              -e AWS_S3_REGION="$AWS_S3_REGION" \
              -e AWS_S3_ACCESS_KEY_ID="$AWS_S3_ACCESS_KEY_ID" \
              -e AWS_S3_SECRET_ACCESS_KEY="$AWS_S3_SECRET_ACCESS_KEY" \
              ${DOCKER_USER}/avalista-be:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
